### ISSUE TITLE
app crashes when using buildtypes to set app name 

### ISSUE THREAD

**Issue by OfekRegev** [YvesCheung/UInspector#4]
I'm using manifestPlaceholders to specify the android:lable manifest value and the app crashes dou to this issue https://stackoverflow.com/questions/49859788/android-labelres-is-0
stacktrace: 
`android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4236)
        at android.app.ActivityThread.access$2200(ActivityThread.java:232)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1998)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:367)
        at android.content.res.Resources.getString(Resources.java:460)
        at android.content.Context.getString(Context.java:639)
        at com.pitaya.mobile.uinspector.notification.UInspectorNotificationService.createNotification(UInspectorNotificationService.kt:65)
        at com.pitaya.mobile.uinspector.notification.UInspectorNotificationService.onStartCommand(UInspectorNotificationService.kt:37)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4218)`

**Comment by YvesCheung** [comment]
Yep, You are right.

**Comment by YvesCheung** [comment]
8ab159ea5c299d9efa24b97d26f625bf0a88d48c Fixed!
