### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by RocketGirls101** [YvesCheung/UInspector#6]
Caused by: java.lang.IllegalArgumentException:Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
        at android.app.PendingIntent.getService(PendingIntent.java:686)
        at com.pitaya.mobile.uinspector.notification.UInspectorNotificationService.createNotification(UInspectorNotificationService.kt:88)
        at com.pitaya.mobile.uinspector.notification.UInspectorNotificationService.onStartCommand(UInspectorNotificationService.kt:37)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)

大佬你好，做Android12适配工作的时候报了这个错误，可以处理一下吗，感谢。

**Comment by YvesCheung** [comment]
今天处理

**Comment by YvesCheung** [comment]
Commit: 6aec6222d735c752308055c665bba07483c82366
Release: 2.0.11
