### ISSUE TITLE
一点通知栏的开关就闪退

### ISSUE THREAD

**Issue by dingxiansen1** [YvesCheung/UInspector#8]
2022-04-29 16:18:36.427 4505-4505/com.incall.navi.bl E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.incall.navi.bl, PID: 4505
    java.lang.RuntimeException: Unable to start service com.pitaya.mobile.uinspector.notification.UInspectorNotificationService@c4c4bcd with Intent { cmp=com.incall.navi.bl/com.pitaya.mobile.uinspector.notification.UInspectorNotificationService (has extras) }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7782af7 -- permission denied for window type 2038
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3376)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1587)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6190)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7782af7 -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:703)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.pitaya.mobile.uinspector.ui.panel.fullscreen.UInspectorWindow.show(UInspectorWindow.kt:35)
        at com.pitaya.mobile.uinspector.UInspector.changePanelState(UInspector.kt:155)
        at com.pitaya.mobile.uinspector.UInspector.changeStateInner$UInspector_Uinspector_api(UInspector.kt:122)
        at com.pitaya.mobile.uinspector.notification.UInspectorNotificationService.onStartCommand(UInspectorNotificationService.kt:38)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3359)
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1587) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6190) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by YvesCheung** [comment]
是android8以下的手机吗？

**Comment by YvesCheung** [comment]
8ae1c6ecf26b393dd1703323c82b3b84b79e1e79
Fix. release v2.0.12

**Comment by dingxiansen1** [comment]
是最新版的模拟器，夜神和雷电都闪退，app是单activity加navgation

**Comment by dingxiansen1** [comment]
> [8ae1c6e](https://github.com/YvesCheung/UInspector/commit/8ae1c6ecf26b393dd1703323c82b3b84b79e1e79) 修复。版本 v2.0.12

是不闪退了，但是没效果了，开启后点了控件跟没点一样

**Comment by YvesCheung** [comment]
我下个模拟器看看

**Comment by dingxiansen1** [comment]
https://user-images.githubusercontent.com/50258853/166854378-ca630daf-8f8b-4fdd-9b3d-e555d9cfecf3.mp4

这是演示，开启之后没效果了

**Comment by dingxiansen1** [comment]
好像显示有问题，这自带的录屏太垃圾了(lll￢ω￢)

**Comment by dingxiansen1** [comment]
https://user-images.githubusercontent.com/50258853/166854967-417e9d8f-87e9-425a-a436-960496f36465.mp4

重新录制了一下，现在可以看清楚了

**Comment by YvesCheung** [comment]
0dd840bb9e345360b3c15d07b92956b405b14a62
v2.0.13

**Comment by dingxiansen1** [comment]
可以来了。大佬牛皮

**Comment by dingxiansen1** [comment]
大佬，我看了一下像素单位都是dp。可以提供其他的单位选择吗比如px.我们的项目全是px写的，要求做到px级对应。/(ㄒoㄒ)/~~

**Comment by YvesCheung** [comment]
改是很好改，把 [ToString.kt](https://github.com/YvesCheung/UInspector/blob/2.x/api/src/main/java/com/pitaya/mobile/uinspector/util/ToString.kt) Int.dpStr 改掉就好。但我没想到什么好的选择方法

**Comment by YvesCheung** [comment]
d2115392da2ba103357dbe2e615be1a2ecf39b63
在应用的 **application** 模块的 **res/** 目录中添加下面资源属性，可以控制使用px而不是dp/sp

```
<resources>
    <!--Use dp (true) or px (false) as unit-->
    <bool name="uinspector_dimension_dp">false</bool>
    <!--Use sp (true) or px (false) as unit-->
    <bool name="uinspector_dimension_sp">false</bool>
</resources>
```

**Comment by dingxiansen1** [comment]
大佬牛皮，棒棒哒




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YvesCheung/UInspector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 中午1:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YvesCheung/UInspector] 一点通知栏的开关就闪退 (Issue #8)





 
d211539
 在应用的 application 模块的 res/ 目录中添加下面资源属性，可以控制使用px而不是dp/sp
 <resources&gt;     <!--Use dp (true) or px (false) as unit--&gt;     <bool name="uinspector_dimension_dp"&gt;false</bool&gt;     <!--Use sp (true) or px (false) as unit--&gt;     <bool name="uinspector_dimension_sp"&gt;false</bool&gt; </resources&gt;
